### PR TITLE
Generate First tests case

### PR DESCRIPTION
**Pull request by SergioRibera**
related #78

### CODE REVIEW

**Comment by SergioRibera** [comment]
@danmt I have noticed that some things are missing from solana, this will require us to have secrets in the repository to take care of the integrity of this sensitive information.

https://github.com/heavy-duty/znap/actions/runs/9899910525/job/27349725940#step:10:482

**Comment by danmt** [comment]
You are right and it also breaks the `deploy`. Due to the `identity` property trying to reach a path that doesn't exist in Github Action's runtime and Shuttle runtime. I created a new issue to track this #83, would love your input there and hear your thoughts.

**Comment by SergioRibera** [comment]
@danmt Using the conversion from base58 it is possible to work this out, it could be considered solved

https://github.com/heavy-duty/znap/actions/runs/9924935167/job/27416920531?pr=82#step:10:508

**Review by danmt — APPROVED** [review]
Apparently this closes #83 in the case of tests.

**Pull request merged**
